Feature/mark node
TPRO-2021/DuckDuckPatent pull request #56
Opened 2021-11-04 13:23 UTC by AlbinaMuzafarova

- node marked once when clicked, twice once the extended preview seen. 
- marks saved to localstorage 

Note: didn't manage to change the background-color of the marked nodes. Any suggestions on a better approach are welcome!!

2021-11-04 20:15 UTC, duaakelzi approved these changes
works very well i like it thank you Abina

2021-11-05 10:00 UTC, micahh2 approved these changes
Awesome Albina!

2021-11-05 11:15 UTC, samuelhuebner requested changes
Works for me 👍🏼 Once you remove the line that causes the patent preview error we can merge that form my point of view

2021-11-05 11:15 UTC, samuelhuebner commented on client/src/components/ResultVisualization.vue
> +            this.$emit('onPatentSelected', { patent: node.patent, index: node.index ?? -1 });
This line causes the patent preview to be broken after clicking a non-patent node. Maybe it got here by accident during a merge?

2021-11-05 11:24 UTC, AlbinaMuzafarova commented
nice catch, thanks Samuel! Have removed the line and tested it on my machine - everything looks to work fine. Merging!

2021-11-05 11:46 UTC, samuelhuebner approved these changes

2021-11-05 11:46 UTC, samuelhuebner commented
> nice catch, thanks Samuel! Have removed the line and tested it on my machine - everything looks to work fine. Merging!

🤩 🚀

2021-11-05 11:54 UTC, merged